nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.3.1.cjs
checksumBehavior: "update"
npmScopes:
    "innoplus-studio":
        npmAlwaysAuth: true
        npmAuthToken: ${GITHUB_TOKEN}
        npmRegistryServer: "https://npm.pkg.github.com"
